# Database
spring:
  datasource:
    url: jdbc:postgresql://database:5432/spring_template_db
    username: postgres
    password: password

  flyway:
    enabled: true
    locations: classpath:db/migration

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000

springfox:
  documentation:
    swagger:
      v2:
        path: /v2/api-docs
